sudo: required

services:
  - docker
language: java

jdk:
  - oraclejdk8

before_install:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ./gpg.sh; fi
  - sudo apt-get install graphviz

install:
  - if [ -z $TRAVIS_TAG ]; then ./mvnw versions:set -DnewVersion=$TRAVIS_TAG; fi
  - ./mvnw clean verify jacoco:report coveralls:report -Possrh
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
  - docker run -d -p8090:8090 -p8091:8091 --name=confluence-publisher-it alainsahli/confluence-publisher-it:6.0.5
  - ./waitForConfluenceStartup.sh confluence-publisher-it 300
  - ./mvnw -Pintegration-tests failsafe:integration-test failsafe:verify
  - ./mvnw -pl asciidoc-confluence-publisher-doc asciidoc-confluence-publisher:publish
  - if [ "$TRAVIS_BRANCH" = "master" ] || [ -z $TRAVIS_TAG ]; then ./mvnw -s .settings.xml jar:jar source:jar javadoc:jar -Dmaven.javadoc.skip=true deploy:deploy -Possrh; fi

cache:
  directories:
  - $HOME/.m2
